### ISSUE TITLE
Should pull up your last search when returning to the app!

### ISSUE THREAD

**Issue by THEjoezack** [codingblocks/podcast-app#11]
That's like..the whole point! (and the same spot in the file to continue listening)

**Comment by Madsn** [comment]
Regarding #13  - It turns out if you don't just refresh the page, but load it in a new tab, you run into this issue: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
So I will change it to simply go to the same spot, and not autoplay - which might have been what you intended anyway.

**Comment by Madsn** [comment]
@THEjoezack Should this be closed?

**Comment by THEjoezack** [comment]
Yes!
