### ISSUE TITLE
Add a tooltip explaining the state of "add" buttons

### ISSUE THREAD

**Issue by dance2die** [codingblocks/podcast-app#155]
#### Show a tooltip on "add" to play list button on hover.
 - "Add to playlist"
#### When an episode is added, the tooltip should show a different message.
- "Already added to the playlist"

## 🤔 Why?
To provide listeners clear description of what buttons mean.
_I looked at the HTML source to find out what they were for_

## Additional context
Buttons in question.
![image](https://user-images.githubusercontent.com/8465237/41822413-2a93fdfc-77bd-11e8-956b-1534cbec02bd.png)

## ⚡️ Side Note
We should probably add tooltips for new buttons being added later on.

**Comment by AdamLantz** [comment]
Perhaps more understandable icons would solve this concern instead? If something isn't intuitive, I don't believe training the user to understand via tooltip is necessarily right

**Comment by davefollett** [comment]
I like the idea of tooltips, but how do those translate to mobile devices?

**Comment by dance2die** [comment]
@davefollett Material design shows [two ways](https://material.io/design/components/tooltips.html#placement) (Scroll down to "Mobile")
1. Long press
1. Show on focus

We could use that industry standard and stick with one.
I prefer the 2nd one (show on focus) but not sure how to implement it, yet.

**Comment by lucask42** [comment]
I agree with @AdamLantz that tooltips are not the smoothest way to teach the user how to use the interface.  Perhaps the icon could be tweaked so that instead of a hamburger icon it looks more like a [list icon](https://codepen.io/lucask42/pen/OEBeON).  Do you think that the list icon along with the transition from 'plus' to 'check' could tell the user what they need to know?  

Perhaps it would help the user to learn if instead of a back-arrow it was a "playlist" button and alert the user to its presence the first time they add something to their list.  Maybe pulsing the color of that button until they click on it.

**Comment by dance2die** [comment]
@lucask42 I am convinced that the tooltip is not the way to go.
As you and @AdamLantz have suggested, it'd be better to have more intuitive design.

Closing 👍 📦
