### ISSUE TITLE
Rewrite the front-end, with testing and modularity as a main concern

### ISSUE THREAD

**Issue by THEjoezack** [codingblocks/podcast-app#21]
For example, the site should be testable, and dependencies like search engines/proxies should be abstracted so they can be swappable

**Comment by Madsn** [comment]
So what's the plan?

**IF** you want to go the framework route:  
I'm a big fan of Vue, but I'd vote React simply because it would be more of a learning experience for me. Can't go wrong with React I guess.
Could use something like [react-snap](https://github.com/stereobooster/react-snap) to build it as a static site, or [gatsbyjs](https://www.gatsbyjs.org/) - but gatsby seems overkill for this, since there is very little static content.

**Comment by THEjoezack** [comment]
I think this has been largely taken care of, need to get the testing going now

**Comment by THEjoezack** [comment]
Going to go ahead and close this, the app has been rewritten and there is 1 test :)
